services:
  nextjs:
    image: zk-website  
    volumes:
      - ./out:/app/.next/static         
    networks:
      - nextjs-net            

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./out:/usr/share/nginx/html/_next/static 
    networks:
      - nextjs-net             
    depends_on:
      - nextjs       # 服务名，在nginx.conf中能用到          

networks:
  nextjs-net:                  
    name: nextjs-net      
    driver: bridge